#ifndef GENESIS_CORE_H
#define GENESIS_CORE_H

/* Generated with cbindgen:0.29.2 */

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Runtime-inspectable tag that mirrors the typestate variants.
 *
 * Usable in status subresources, audit events, and FFI where generics
 * are not available. Stable `repr(C)` numbering for the Go host.
 */
typedef enum StateTag {
  UNINITIALIZED = 0,
  INITIALIZED = 1,
  BOOTSTRAPPING = 2,
  ACTIVE = 3,
  ROTATING = 4,
  DEGRADED = 5,
} StateTag;

/**
 * Opaque handle that the Go host uses to refer to a genesis-core
 * state machine instance.
 *
 * The `ptr` field points to a heap-allocated [`GenesisInner`] enum.
 * The `state` field mirrors the current typestate for runtime dispatch.
 */
typedef struct GenesisHandle {
  void *ptr;
  enum StateTag state;
} GenesisHandle;

/**
 * Result type returned by every FFI function.
 *
 * On success: `success == true`, `handle` is valid, `error_code == 0`.
 * On failure: `success == false`, `error_code` is non-zero,
 *             `error_message` is a NUL-terminated UTF-8 string (caller
 *             must free with `genesis_free_string`).
 *
 * `data_json` carries serialised JSON for functions that return extra
 * data (PublicArtifacts, VerifyResult, GenesisStatus).  NULL when no
 * data is returned.  Caller must free with `genesis_free_string`.
 */
typedef struct GenesisResult {
  bool success;
  uint32_t error_code;
  char *error_message;
  struct GenesisHandle handle;
  char *data_json;
} GenesisResult;

/**
 * C-compatible audit callback signature.
 *
 * The callee receives a pointer to UTF-8 JSON and its byte length.
 * Data must be copied if it needs to outlive the call.
 * Pass a null function pointer for no-op audit.
 */
typedef void (*AuditCallback)(const uint8_t *data, uintptr_t len);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new genesis-core instance in the `Uninitialized` state.
 *
 * `config_json` is a NUL-terminated UTF-8 JSON string that deserialises
 * to a [`GenesisConfig`].  `audit_cb` is an optional audit callback; pass
 * NULL for a no-op sink.
 *
 * # Safety
 *
 * `config_json` must be a valid NUL-terminated C string or NULL.
 */
struct GenesisResult genesis_new(const char *config_json, AuditCallback audit_cb);

/**
 * Generate a keypair, KMS-encrypt the private key, and transition to
 * `Initialized`.
 *
 * On success, `data_json` contains JSON-serialised [`PublicArtifacts`].
 *
 * # Safety
 *
 * `handle` must be a valid `GenesisHandle` in the `Uninitialized` state.
 * `kms_config_json` must be a valid NUL-terminated C string.
 */
struct GenesisResult genesis_init(struct GenesisHandle handle, const char *kms_config_json);

/**
 * Load a previously-persisted keypair and transition to `Initialized`.
 *
 * # Safety
 *
 * `handle` must be a valid `GenesisHandle` in the `Uninitialized` state.
 * `public_key` must be a valid NUL-terminated C string.
 * `envelope_ciphertext` + `envelope_len` must point to a valid byte buffer.
 */
struct GenesisResult genesis_load(struct GenesisHandle handle,
                                  const char *public_key,
                                  const uint8_t *envelope_ciphertext,
                                  uintptr_t envelope_len);

/**
 * Verify the stored envelope by decrypting and re-deriving the public key.
 *
 * On success, writes a JSON-serialised [`VerifyResult`] to `*result_json_out`
 * (caller must free with `genesis_free_string`).
 *
 * # Safety
 *
 * `handle` must be a valid `GenesisHandle` in the `Initialized` state.
 * `kms_config_json` must be a valid NUL-terminated C string.
 * `result_json_out` must point to a valid `*mut c_char` to receive the
 * result JSON (caller must free with `genesis_free_string`).
 */
struct GenesisResult genesis_verify(struct GenesisHandle handle,
                                    const char *kms_config_json,
                                    char **result_json_out);

/**
 * Decrypt the envelope and transition to `Bootstrapping`.
 *
 * # Safety
 *
 * `handle` must be a valid `GenesisHandle` in the `Initialized` state.
 * `kms_config_json` must be a valid NUL-terminated C string.
 */
struct GenesisResult genesis_begin_bootstrap(struct GenesisHandle handle,
                                             const char *kms_config_json);

/**
 * Inject the decrypted key material into a Kubernetes secret and
 * transition to `Active`.
 *
 * # Safety
 *
 * `handle` must be a valid `GenesisHandle` in the `Bootstrapping` state.
 * String parameters must be valid NUL-terminated C strings.
 */
struct GenesisResult genesis_inject_secret(struct GenesisHandle handle,
                                           const char *secret_name,
                                           const char *secret_namespace,
                                           const char *secret_key);

/**
 * Return a JSON-serialised status snapshot.
 *
 * On success, writes JSON to `*status_json_out` (caller must free with
 * `genesis_free_string`), and also sets `data_json` on the result.
 *
 * # Safety
 *
 * `handle` must be a valid `GenesisHandle` in the `Active` state.
 * `status_json_out` must point to a valid `*mut c_char`.
 */
struct GenesisResult genesis_status(struct GenesisHandle handle, char **status_json_out);

/**
 * Begin a key rotation cycle, transitioning to `Rotating`.
 *
 * # Safety
 *
 * `handle` must be a valid `GenesisHandle` in the `Active` state.
 */
struct GenesisResult genesis_begin_rotation(struct GenesisHandle handle);

/**
 * Complete the rotation: generate new keypair, re-encrypt, inject,
 * transition to `Active`.
 *
 * On success, `data_json` contains JSON-serialised [`PublicArtifacts`].
 *
 * # Safety
 *
 * `handle` must be a valid `GenesisHandle` in the `Rotating` state.
 * String parameters must be valid NUL-terminated C strings.
 */
struct GenesisResult genesis_complete_rotation(struct GenesisHandle handle,
                                               const char *kms_config_json,
                                               const char *secret_name,
                                               const char *secret_namespace,
                                               const char *secret_key);

/**
 * Free a `GenesisHandle` and all associated resources.
 *
 * After this call the handle is invalid and must not be used.
 * Passing a NULL pointer is a safe no-op.
 *
 * # Safety
 *
 * `handle.ptr` must be a valid pointer returned by one of the genesis
 * functions, or NULL.
 */
void genesis_free(struct GenesisHandle handle);

/**
 * Free a NUL-terminated string previously returned by genesis-core.
 *
 * Passing a NULL pointer is a safe no-op.
 *
 * # Safety
 *
 * `s` must be a pointer returned by one of the genesis functions (as an
 * error message, data_json, or result string), or NULL.
 */
void genesis_free_string(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GENESIS_CORE_H */
