apiVersion: v2
name: genesis-operator
description: A Helm chart for the Genesis GitOps Secrets Bootstrap Operator
type: application
version: 0.2.0
appVersion: "0.3.0"
keywords:
  - secrets
  - gitops
  - sops
  - age
  - encryption
  - kubernetes
  - operator
home: https://github.com/larsenclose/genesis
sources:
  - https://github.com/larsenclose/genesis
maintainers:
  - name: genesis-maintainers
