//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSIRSASpec) DeepCopyInto(out *AWSIRSASpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSIRSASpec.
func (in *AWSIRSASpec) DeepCopy() *AWSIRSASpec {
	if in == nil {
		return nil
	}
	out := new(AWSIRSASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSKmsSpec) DeepCopyInto(out *AWSKmsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSKmsSpec.
func (in *AWSKmsSpec) DeepCopy() *AWSKmsSpec {
	if in == nil {
		return nil
	}
	out := new(AWSKmsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttestationSpec) DeepCopyInto(out *AttestationSpec) {
	*out = *in
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCSpec)
		**out = **in
	}
	if in.AWSIRSA != nil {
		in, out := &in.AWSIRSA, &out.AWSIRSA
		*out = new(AWSIRSASpec)
		**out = **in
	}
	if in.GCPWorkloadIdentity != nil {
		in, out := &in.GCPWorkloadIdentity, &out.GCPWorkloadIdentity
		*out = new(GCPWorkloadIdentitySpec)
		**out = **in
	}
	if in.GitHubActions != nil {
		in, out := &in.GitHubActions, &out.GitHubActions
		*out = new(GitHubActionsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttestationSpec.
func (in *AttestationSpec) DeepCopy() *AttestationSpec {
	if in == nil {
		return nil
	}
	out := new(AttestationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttestationStatus) DeepCopyInto(out *AttestationStatus) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttestationStatus.
func (in *AttestationStatus) DeepCopy() *AttestationStatus {
	if in == nil {
		return nil
	}
	out := new(AttestationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureKeyVaultSpec) DeepCopyInto(out *AzureKeyVaultSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureKeyVaultSpec.
func (in *AzureKeyVaultSpec) DeepCopy() *AzureKeyVaultSpec {
	if in == nil {
		return nil
	}
	out := new(AzureKeyVaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvelopeSpec) DeepCopyInto(out *EnvelopeSpec) {
	*out = *in
	if in.AWSKms != nil {
		in, out := &in.AWSKms, &out.AWSKms
		*out = new(AWSKmsSpec)
		**out = **in
	}
	if in.GCPKms != nil {
		in, out := &in.GCPKms, &out.GCPKms
		*out = new(GCPKmsSpec)
		**out = **in
	}
	if in.AzureKeyVault != nil {
		in, out := &in.AzureKeyVault, &out.AzureKeyVault
		*out = new(AzureKeyVaultSpec)
		**out = **in
	}
	if in.OCIVault != nil {
		in, out := &in.OCIVault, &out.OCIVault
		*out = new(OCIVaultSpec)
		**out = **in
	}
	if in.YubiKey != nil {
		in, out := &in.YubiKey, &out.YubiKey
		*out = new(YubiKeySpec)
		**out = **in
	}
	if in.TPM != nil {
		in, out := &in.TPM, &out.TPM
		*out = new(TPMSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvelopeSpec.
func (in *EnvelopeSpec) DeepCopy() *EnvelopeSpec {
	if in == nil {
		return nil
	}
	out := new(EnvelopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKmsSpec) DeepCopyInto(out *GCPKmsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKmsSpec.
func (in *GCPKmsSpec) DeepCopy() *GCPKmsSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKmsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPWorkloadIdentitySpec) DeepCopyInto(out *GCPWorkloadIdentitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPWorkloadIdentitySpec.
func (in *GCPWorkloadIdentitySpec) DeepCopy() *GCPWorkloadIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(GCPWorkloadIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisBootstrap) DeepCopyInto(out *GenesisBootstrap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisBootstrap.
func (in *GenesisBootstrap) DeepCopy() *GenesisBootstrap {
	if in == nil {
		return nil
	}
	out := new(GenesisBootstrap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenesisBootstrap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisBootstrapList) DeepCopyInto(out *GenesisBootstrapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GenesisBootstrap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisBootstrapList.
func (in *GenesisBootstrapList) DeepCopy() *GenesisBootstrapList {
	if in == nil {
		return nil
	}
	out := new(GenesisBootstrapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenesisBootstrapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisBootstrapSpec) DeepCopyInto(out *GenesisBootstrapSpec) {
	*out = *in
	in.Envelope.DeepCopyInto(&out.Envelope)
	if in.Attestation != nil {
		in, out := &in.Attestation, &out.Attestation
		*out = new(AttestationSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Output.DeepCopyInto(&out.Output)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisBootstrapSpec.
func (in *GenesisBootstrapSpec) DeepCopy() *GenesisBootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(GenesisBootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisBootstrapStatus) DeepCopyInto(out *GenesisBootstrapStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAttestation != nil {
		in, out := &in.LastAttestation, &out.LastAttestation
		*out = new(AttestationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.KeyMetadata != nil {
		in, out := &in.KeyMetadata, &out.KeyMetadata
		*out = new(KeyMetadata)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisBootstrapStatus.
func (in *GenesisBootstrapStatus) DeepCopy() *GenesisBootstrapStatus {
	if in == nil {
		return nil
	}
	out := new(GenesisBootstrapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisRotationPolicy) DeepCopyInto(out *GenesisRotationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisRotationPolicy.
func (in *GenesisRotationPolicy) DeepCopy() *GenesisRotationPolicy {
	if in == nil {
		return nil
	}
	out := new(GenesisRotationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenesisRotationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisRotationPolicyList) DeepCopyInto(out *GenesisRotationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GenesisRotationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisRotationPolicyList.
func (in *GenesisRotationPolicyList) DeepCopy() *GenesisRotationPolicyList {
	if in == nil {
		return nil
	}
	out := new(GenesisRotationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenesisRotationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisRotationPolicySpec) DeepCopyInto(out *GenesisRotationPolicySpec) {
	*out = *in
	out.Source = in.Source
	out.Schedule = in.Schedule
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(RotationStrategySpec)
		**out = **in
	}
	if in.Notify != nil {
		in, out := &in.Notify, &out.Notify
		*out = make([]NotificationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisRotationPolicySpec.
func (in *GenesisRotationPolicySpec) DeepCopy() *GenesisRotationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GenesisRotationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisRotationPolicyStatus) DeepCopyInto(out *GenesisRotationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastRotation != nil {
		in, out := &in.LastRotation, &out.LastRotation
		*out = new(RotationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.NextRotation != nil {
		in, out := &in.NextRotation, &out.NextRotation
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisRotationPolicyStatus.
func (in *GenesisRotationPolicyStatus) DeepCopy() *GenesisRotationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GenesisRotationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubActionsSpec) DeepCopyInto(out *GitHubActionsSpec) {
	*out = *in
	if in.RefPatterns != nil {
		in, out := &in.RefPatterns, &out.RefPatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedActors != nil {
		in, out := &in.AllowedActors, &out.AllowedActors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubActionsSpec.
func (in *GitHubActionsSpec) DeepCopy() *GitHubActionsSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubActionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyMetadata) DeepCopyInto(out *KeyMetadata) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyMetadata.
func (in *KeyMetadata) DeepCopy() *KeyMetadata {
	if in == nil {
		return nil
	}
	out := new(KeyMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationSpec) DeepCopyInto(out *NotificationSpec) {
	*out = *in
	if in.WebhookSecretRef != nil {
		in, out := &in.WebhookSecretRef, &out.WebhookSecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationSpec.
func (in *NotificationSpec) DeepCopy() *NotificationSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIVaultSpec) DeepCopyInto(out *OCIVaultSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIVaultSpec.
func (in *OCIVaultSpec) DeepCopy() *OCIVaultSpec {
	if in == nil {
		return nil
	}
	out := new(OCIVaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCSpec) DeepCopyInto(out *OIDCSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCSpec.
func (in *OIDCSpec) DeepCopy() *OIDCSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputSpec) DeepCopyInto(out *OutputSpec) {
	*out = *in
	if in.AdditionalNamespaces != nil {
		in, out := &in.AdditionalNamespaces, &out.AdditionalNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputSpec.
func (in *OutputSpec) DeepCopy() *OutputSpec {
	if in == nil {
		return nil
	}
	out := new(OutputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCRSelection) DeepCopyInto(out *PCRSelection) {
	*out = *in
	if in.PCRs != nil {
		in, out := &in.PCRs, &out.PCRs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCRSelection.
func (in *PCRSelection) DeepCopy() *PCRSelection {
	if in == nil {
		return nil
	}
	out := new(PCRSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationScheduleSpec) DeepCopyInto(out *RotationScheduleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationScheduleSpec.
func (in *RotationScheduleSpec) DeepCopy() *RotationScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(RotationScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationSourceSpec) DeepCopyInto(out *RotationSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationSourceSpec.
func (in *RotationSourceSpec) DeepCopy() *RotationSourceSpec {
	if in == nil {
		return nil
	}
	out := new(RotationSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationStatus) DeepCopyInto(out *RotationStatus) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationStatus.
func (in *RotationStatus) DeepCopy() *RotationStatus {
	if in == nil {
		return nil
	}
	out := new(RotationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationStrategySpec) DeepCopyInto(out *RotationStrategySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationStrategySpec.
func (in *RotationStrategySpec) DeepCopy() *RotationStrategySpec {
	if in == nil {
		return nil
	}
	out := new(RotationStrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TPMSpec) DeepCopyInto(out *TPMSpec) {
	*out = *in
	if in.PCRSelection != nil {
		in, out := &in.PCRSelection, &out.PCRSelection
		*out = new(PCRSelection)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TPMSpec.
func (in *TPMSpec) DeepCopy() *TPMSpec {
	if in == nil {
		return nil
	}
	out := new(TPMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YubiKeySpec) DeepCopyInto(out *YubiKeySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YubiKeySpec.
func (in *YubiKeySpec) DeepCopy() *YubiKeySpec {
	if in == nil {
		return nil
	}
	out := new(YubiKeySpec)
	in.DeepCopyInto(out)
	return out
}
